name: Build and Deploy

on:
  workflow_call:
    inputs:
      ecr_repo:
        required: false
        type: string
      s3_bucket_name:
        required: false
        type: string
      cloudfront_distribution_id:
        required: false
        type: string
      main_branch:
        required: false
        type: string
      prod_repository_uri:
        required: true
        type: string
      repository_uri:
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: your-repo-name
  PROD_REPOSITORY_URI: ${{ inputs.prod_repository_uri }}
  REPOSITORY_URI: ${{ inputs.repository_uri }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # contents: read
      # packages: write
      # id-token: write
    steps:
      - name: Get called workflow reference
        run: |
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

      - name: Pull cache image
        run: docker pull $REPOSITORY_URI:latest || true

      - name: Build, tag
        run: |
          IMAGE_TAG=build-${{ github.run_id }}
          docker build --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:latest . --build-arg GITHUB_TOKEN=$GITHUB_TOKEN
          docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
          repo_name="${REPOSITORY_URI##*/}"
          echo "$repo_name"
          aws ecr put-image-tag-mutability --repository-name $repo_name --image-tag-mutability MUTABLE --region $AWS_REGION
          docker push $REPOSITORY_URI:latest
          aws ecr put-image-tag-mutability --repository-name $repo_name --image-tag-mutability IMMUTABLE --region $AWS_REGION

      - name: Extract tag
        run: |
          git fetch --tags
          echo "git_ref=$(git describe --tags --abbrev=0 --always)" >> "$GITHUB_ENV"
          echo $git_ref

      - name: Push Docker images to ECR1
        run: |
          echo $git_ref
          docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$git_ref
          docker push $REPOSITORY_URI:$git_ref

      - name: Push Docker images to ECR2
        run: |
          echo $GITHUB_REF_NAME
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $PROD_REPOSITORY_URI
          docker tag $REPOSITORY_URI:latest $PROD_REPOSITORY_URI:$git_ref
          docker push $PROD_REPOSITORY_URI:$git_ref
        env:
          aws-access-key-id: ${{ secrets.TF_VAR_aws_access_key }}
          aws-secret-access-key: ${{ secrets.TF_VAR_aws_secret_key }}
          aws-region: ${{ env.AWS_REGION }}
